---
name: single partition, group is partition
driver:
  name: docker
platforms:
  - name: testohpc-control
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    groups:
      - testohpc_control
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
    docker_networks:
      - name: net1
        driver_options:
          com.docker.network.driver.mtu: ${DOCKER_MTU:-1500} # 1500 is docker default
provisioner:
  name: ansible
verifier:
  name: ansible
